#!/usr/bin/env bash
# Extrahiert File-Meta aus dem Repo — kein nix eval, kein build.
# .nix/.sh: "# ---" Blöcke mit "# key: value" (kommentiertes YAML)
# .md:      YAML-Frontmatter zwischen "---"
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:---stdout}"

emit_doc() {
  local path="$1"
  local rel="${path#$ROOT/}"
  # Nur Frontmatter am Dateianfang (Zeile 1 = ---), nicht horizontale Regeln im Fließtext
  head -n 40 "$path" | awk -v rel="$rel" '
    NR == 1 && $0 != "---" { exit 1 }
    BEGIN { in_fm=0; n=0 }
    /^---$/ {
      if (in_fm) { exit }
      in_fm=1; next
    }
    in_fm {
      print
      n++
    }
    END { if (n==0) exit 1 }
  ' | sed "1i\\
file: $rel
" || return 1
}

emit_comment_block() {
  local path="$1"
  local rel="${path#$ROOT/}"
  awk -v rel="$rel" '
    BEGIN { in_b=0; buf="" }
    /^# ---$/ {
      if (in_b) {
        sub(/^# /, "", buf)
        gsub(/\n# /, "\n", buf)
        if (buf ~ /meta:/) {
          print "file: " rel
          print buf
          print "---"
        }
        in_b=0; buf=""
        next
      }
      in_b=1; next
    }
    in_b && /^# / { buf = buf (buf ? "\n" : "") substr($0, 3); next }
    in_b && /^#$/ { buf = buf (buf ? "\n" : "") ""; next }
  ' "$path"
}

scan_tree() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  find "$dir" -type f \( -name '*.nix' -o -name '*.sh' -o -name '*.md' \) \
    ! -path '*/.git/*' ! -path '*/.grok/*' | sort
}

build_index() {
  echo "# Generated by tools/list-file-meta.sh — do not edit"
  echo "schema: meta/schema.yaml"
  echo "entries:"
  local any=0
  while IFS= read -r f; do
    local chunk=""
    case "$f" in
      *.md) chunk=$(emit_doc "$f" 2>/dev/null || true) ;;
      *)    chunk=$(emit_comment_block "$f" 2>/dev/null || true) ;;
    esac
    [[ -n "$chunk" ]] || continue
    any=1
    echo "  - |"
    echo "$chunk" | sed 's/^/    /'
  done < <(
    scan_tree "$ROOT/modules"
    scan_tree "$ROOT/lib"
    scan_tree "$ROOT/machines"
    scan_tree "$ROOT/users"
    scan_tree "$ROOT/packages"
    scan_tree "$ROOT/tools"
    scan_tree "$ROOT/docs"
    find "$ROOT" -maxdepth 1 -type f \( -name '*.nix' -o -name '*.md' \) | sort
  )
  [[ "$any" -eq 1 ]] || echo "  []"
}

case "$MODE" in
  --stdout)
    build_index
    ;;
  --write)
    build_index > "$ROOT/meta/index.yaml"
    echo "Wrote $ROOT/meta/index.yaml"
    ;;
  *)
    echo "Usage: $0 [--stdout|--write]" >&2
    exit 1
    ;;
esac